version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      effect:
        patterns:
          - "effect"
          - "@effect/*"
    ignore:
      - dependency-name: "vitest"
        update-types: ["version-update:semver-major"]
